from PyPDFForm import PdfWrapper

filled = PdfWrapper("template.pdf").fill(
    {
        "Agenda": "test_1",
        "Agenda 1": "test_2",
        "Agenda 2": "test_3",
        "Agenda 3": "test_4",
        "Agenda 4": "test_5",
        "Attendees": "test_6",
        "Attendees 1": "test_7",
        "Attendees 2": "test_8",
        "Attendees 3": "test_9",
        "Attendees 4": "test_10",
        "Check Box 1": True,
        "Check Box 2": True,
        "Check Box 3": True,
        "Check Box 4": True,
        "Check Box 5": True,
        "Check Box 6": True,
        "Check Box 7": True,
        "Date": "test_11",
        "Due" : "test_12",
        "Due 1": "test_13",
        "Due 2": "test_14",
        "Due 3": "test_15",
        "Due 4": "test_16",
        "Due 5": "test_17",
        "Due 6": "test_18",
        "Location": "test_19",
        "Meeting notes": "test_20",
        "Owner": "test_21",
        "Owner 1": "test_22",
        "Owner 2": "test_23",
        "Owner 3": "test_24",
        "Owner 4": "test_25",
        "Owner 5": "test_26",
        "Owner 6": "test_27",
        "Purpose": "test_28",
        "Recorded by": "test_29",
        "Task": "test_30",
        "Task 1": "test_31",
        "Task 2": "test_32",
        "Task 3": "test_33",
        "Task 4": "test_34",
        "Task 5": "test_35",
        "Task 6": "test_36",
        "Time": "test_37",
        "Title": "test_38",
    },
)

with open("fillout.pdf", "wb+") as output:
    output.write(filled.read())
